[FEAT] 마이페이지 개발
SystemConsultantGroup/S-top-frontend pull request #107
Opened 2024-11-07 07:31 UTC by sera2002

작성자: @sera2002 
이슈: #41 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 마이페이지 화면 구현 (API 연결 X)

## 비고

- 마이페이지 API가 아직 리뷰 중이라서 일단 API 연결 없이 올려놓겠습니다.

close/resolve/fix #{이슈 번호 기입}

2025-01-14 08:10 UTC, chunzhi23 requested changes

2025-01-14 08:10 UTC, chunzhi23 commented on src/components/pages/MyPage/MypageForm.module.css
> +}
height를 퍼센트 대신 px 또는 vh와 같이 안정적인 단위를 쓰면 좋겠습니다.

2025-01-14 08:10 UTC, chunzhi23 commented on src/components/pages/MyPage/MypageForm.module.css
> +  flex-shrink: 0;
요것도 height를 퍼센트 대신 px 또는 vh와 같이 안정적인 단위를 쓰면 좋겠습니다!

2025-01-14 08:10 UTC, chunzhi23 commented on src/components/pages/MyPage/MypageUserInfo.tsx
> +    // TODO: 정보 업데이트 완료 알림
혹시 TODO 해결된건가요?

2025-01-14 08:10 UTC, chunzhi23 commented on src/components/pages/MyPage/MypageView.module.css
> +  flex-shrink: 0;
퍼센트 확인 부탁드립니다!

2025-01-17 05:04 UTC, sera2222 commented on src/components/pages/MyPage/MypageUserInfo.tsx
> +    // TODO: 정보 업데이트 완료 알림
이 TODO는 아직 해결 안하긴 했습니다.

2025-01-17 05:04 UTC, sera2222 commented on src/components/pages/MyPage/MypageForm.module.css
> +  flex-shrink: 0;
이 부분 수정했습니다. 확인 부탁드려요!

2025-01-17 05:05 UTC, sera2222 commented on src/components/pages/MyPage/MypageForm.module.css
> +}
이 부분 수정했습니다. 확인 부탁드려요!

2025-01-17 05:05 UTC, sera2222 commented on src/app/(user)/mypage/page.tsx
> +import { MypageView } from "@/components/pages/MyPage/MypageView";
말씀하신대로 수정했습니다. 확인 부탁드립니다!

2025-01-17 05:09 UTC, sera2222 commented on src/components/pages/MyPage/MypageView.module.css
> +  flex-shrink: 0;
넵 수정했습니다!

2025-01-21 05:32 UTC, chunzhi23 approved these changes
감사합니다!

2025-01-21 05:33 UTC, merged