[FEAT] 드롭다운 컴포넌트 #7
SystemConsultantGroup/s-top-frontend pull request #16
Opened 2024-07-17 05:41 UTC by moony1204

작성자: @moony1204 

## 체크 리스트

- [v] 적절한 제목으로 수정했나요?
- [v] 상단에 이슈 번호를 기입했나요?
- [v] Target Branch를 올바르게 설정했나요?
- [v] Label을 알맞게 설정했나요?

## 작업 내역

- 드롭다운 컴포넌트 작업

## 비고

- 기능적으로는 괜찮은 듯 한데 디자인은 좀 수정이 필요합니다
- 일단 확인/점검 차원에서 pr 올립니다

2024-07-24 05:40 UTC, chunzhi23 commented
`Dropdown.module.css` 스타일 문서에서 `.dropdown`에 대한 스타일이 정의되어 있는데 사용하지 않는 코드 같아서 수정해주시면 좋을 것 같습니다.

피그마 디자인에서는 dropdown list를 펼쳤을 때 토글과 가까이 붙어있는데 동작하는 코드에선 띄어져있어서 설명을 부탁드리고 싶습니다. 다음과 같이 띄어낼 수 있어요:
```
// Dropdown.tsx
<Menu offset={0}>...</Menu>
```

그리고 토글이 hover 되었을 때 mantine 기본 스타일로 나오는데 이 부분 수정해주시면 좋을 것 같습니다.
```
// Dropdown.module.css
.dropdownToggle:hover {
  background-color: #F5F5F5;
  color: #000;
}
```

마지막으로 드롭다운 아이템 리스트 전체에 패딩이 있어가지고 없애면 좋겠다는 개인적인 생각이 있어서 설명을 부탁드리고 싶습니다. 다음과 같이 없앨 수 있어요:

그리고 토글이 hover 되었을 때 mantine 기본 스타일로 나오는데 이 부분 수정해주시면 좋을 것 같습니다.
```
// Dropdown.tsx
<Menu.Dropdown className={classes.dropdownList}>...</>

// Dropdown.module.css
.dropdownToggle:hover {
  background-color: #F5F5F5;
  color: #000;
}
```

2024-07-24 05:45 UTC, chunzhi23 reviewed
`Dropdown.module.css` 스타일 문서에서 `.dropdown`에 대한 스타일이 정의되어 있는데 사용하지 않는 코드 같아서 수정해주시면 좋을 것 같습니다.

피그마 디자인에서는 dropdown list를 펼쳤을 때 토글과 가까이 붙어있는데 동작하는 코드에선 띄어져있어서 설명을 부탁드리고 싶습니다. 다음과 같이 띄어낼 수 있어요:
```
// Dropdown.tsx
<Menu offset={0}>...</Menu>
```

그리고 토글이 hover 되었을 때 mantine 기본 스타일로 나오는데 이 부분 수정해주시면 좋을 것 같습니다.
```
// Dropdown.module.css
.dropdownToggle:hover {
  background-color: #F5F5F5;
  color: #000;
}
```

마지막으로 드롭다운 아이템 리스트 전체에 패딩이 있어가지고 없애면 좋겠다는 개인적인 생각이 있어서 설명을 부탁드리고 싶습니다. 다음과 같이 없앨 수 있어요:

그리고 토글이 hover 되었을 때 mantine 기본 스타일로 나오는데 이 부분 수정해주시면 좋을 것 같습니다.
```
// Dropdown.tsx
<Menu.Dropdown className={classes.dropdownList}>...</>

// Dropdown.module.css
.dropdownToggle:hover {
  background-color: #F5F5F5;
  color: #000;
}
```

2024-07-27 06:43 UTC, chunzhi23 requested changes
고생하셨습니다. 아래 수정사항 외에는 이후 라이트/다크 색상을 찬찬히 바꾸면 좋을 것 같습니다!

2024-07-27 06:43 UTC, chunzhi23 commented on src/components/common/Dropdown/Dropdown.tsx
> +      <Menu.Target>
`Component.XXX`와 같이 . 을 사용해서 컴포넌트를 불러오면 use client 미작성 시 오류가 날 수도 있다고 하니 `MenuTarget` 컴포넌트를 따로 가져와 사용하면 좋을 것 같습니다!

[Compound components in server components](https://mantine.dev/guides/next/#compound-components-in-server-components)를 한번 참고해주세요 :>

2024-07-27 06:43 UTC, chunzhi23 commented on src/components/common/Dropdown/Dropdown.tsx
> +                <svg
svg 형식으로 바로 아이콘을 입력하면 나중에 알아보기 힘들 것 같아 Tabler 사용을 권해드립니다!

[Tabler Icons](https://tabler.io/icons)에서 원하는 아이콘을 검색한 후 아래 빨간색 네모 박스 위치에 적혀있는 이름을 확인해주세요.
클릭하시면 복사가 됩니다!

![image](https://github.com/user-attachments/assets/d26ef889-a48e-4879-bfd3-3675816cf0cb)

그럼 vscode에서 컴포넌트 같이 사용할 수 있습니다!

![image](https://github.com/user-attachments/assets/84a5b583-ce02-42a2-8fd3-44e3f928e41a)

- size: 크기
- stroke: 굵기

참고해주시면 좋을 것 같습니다 :)

2024-07-27 06:43 UTC, chunzhi23 commented on src/components/common/Dropdown/Dropdown.tsx
> +                <svg
이 친구도 Tabler Component 또는 무슨 아이콘인지 주석을 달아주시면 좋을 것 같습니다.

2024-07-27 06:43 UTC, chunzhi23 commented on src/components/common/Dropdown/Dropdown.tsx
> +      <Menu.Dropdown className={classes.dropdownList}>
`MenuTarget`과 마찬가지로 `MenuDropdown`을 가져와 대신 사용해주시면 좋겠습니다!

2024-07-27 06:43 UTC, chunzhi23 commented on src/components/common/Dropdown/Dropdown.tsx
> +          <Menu.Item
`MenuItem`을 대신 사용하시면 좋겠습니다!

2024-07-31 01:02 UTC, moony1204 commented on src/components/common/Dropdown/Dropdown.tsx
> +      <Menu.Target>
반영 했습니다

2024-07-31 01:02 UTC, moony1204 commented on src/components/common/Dropdown/Dropdown.tsx
> +                <svg
암만 봐도 tabler에 맘에 드는 아이콘이 없어서 그냥 아이콘 정보 코멘트 해두었습니다ㅠ

2024-07-31 01:04 UTC, merged

2024-07-31 06:58 UTC, chunzhi23 reviewed
고생 많으셨습니다🙇