[Feat] 버튼 추가
SystemConsultantGroup/s-top-frontend pull request #24
Opened 2024-07-19 05:25 UTC by sera2002

작성자: @sera2002 
이슈: #8 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- secondary button, outlined button, danger button을 추가하였습니다.
- primary button의 스타일을 수정하였습니다.

## 비고

- 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.

close/resolve/fix #{이슈 번호 기입}

2024-07-23 03:29 UTC, obinox approved these changes
문제없는 것 같습니다

2024-07-27 10:54 UTC, chunzhi23 requested changes
고생하셨습니다. 개인적인 생각으로 disabled의 경우 회색 톤의 살짝 흐려지는 느낌이 좋을 것 같다고 느끼는데 추후 논의를 거쳐서 확정지으면 좋을 것 같습니다!

2024-07-27 10:54 UTC, chunzhi23 commented on src/components/common/Buttons/OutlinedButton/OutlinedButton.module.css
> +    border: 1px solid var(--color-outineVariant);
오탈자가 발생해서 색상이 적용되지 않는 것 같아 다시 한 번 확인을 부탁드리겠습니다!
```
outlineVariant
```

2024-08-07 09:02 UTC, sera2002 commented on src/components/common/Buttons/OutlinedButton/OutlinedButton.module.css
> +    border: 1px solid var(--color-outineVariant);
오탈자 수정했으니 확인해보시고 문제 없으면 resolve 부탁드립니다!

2024-08-08 13:51 UTC, merged