[Feat] 프로젝트 선택 탭 추가
SystemConsultantGroup/s-top-frontend pull request #25
Opened 2024-07-19 05:32 UTC by sera2002

작성자: @sera2002 
이슈: #8 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 프로젝트 선택 탭을 추가하였습니다.

## 비고

- 스토리 canvas 너비 제한 때문에 탭 부분이 줄바꿈이 되어 보이는데, 실제로 페이지에 적용하면 정상적으로 표시되긴 합니다.

close/resolve/fix #{이슈 번호 기입}

2024-07-23 07:32 UTC, obinox approved these changes
문제없어 보입니다

2024-07-27 11:16 UTC, chunzhi23 requested changes
고생하셨습니다. 아래 수정사항 외에 라이트/다크 색상을 차후 수정해보면 좋을 것 같습니다!

2024-07-27 11:16 UTC, chunzhi23 commented on src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.tsx
> +        <Tabs.List grow={grow} className={classes.tablist}>
`Component.XXX`와 같이 . 을 사용해서 컴포넌트를 불러오면 use client 미작성 시 오류가 날 수도 있다고 하니 `TabsList` 컴포넌트를 따로 가져와 사용하면 좋을 것 같습니다!

[Compound components in server components](https://mantine.dev/guides/next/#compound-components-in-server-components)를 한번 참고해주세요 :D

2024-07-27 11:16 UTC, chunzhi23 commented on src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.tsx
> +            <Tabs.Tab
`TabsList`와 마찬가지로 `TabsTab`을 가져와 별도로 사용해주시면 좋겠습니다!

2024-07-27 11:16 UTC, chunzhi23 commented on src/components/common/Tabs/ProjectSelectTab/ProjectSelectTab.tsx
> +  content: ReactNode;
content라는 props 대신 children으로 탭 내용을 받으면 어떨까는 개인적인 생각이 들었습니다! 검토해주시면 감사하겠습니다🙇

2024-08-09 05:06 UTC, chunzhi23 approved these changes

2024-08-09 06:05 UTC, merged