[FEAT] 헤더
SystemConsultantGroup/s-top-frontend pull request #26
Opened 2024-07-19 06:44 UTC by chunzhi23

작성자: @chunzhi23
Issue: #5

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 헤더 컴포넌트 코드를 작성했습니다.

## 비고

- 반응형 디자인을 임시로 만들어 두었습니다. 논의를 통해 추후 보완이 필요해 보입니다.
- theme color가 figma에 작성되어 있는 것과 조금 차이를 보였기에 hex로 우선 작성했습니다. 추후 보완이 필요합니다.

2024-07-25 06:25 UTC, hynseok requested changes
만들기 어려운 컴포넌트였을텐데, 잘 만들어주신 것 같습니다. 수고하셨고, 간단한 수정사항 확인 부탁드립니다!

2024-07-25 06:25 UTC, hynseok commented on src/components/common/Header/Header.tsx
> +        <HeaderSymbol />
HeaderSymbol 혹은 HeaderSymbol 안의 이미지를 클릭하면 사이트의 루트로 이동하는 기능이 있으면 좋을 것 같습니다!

2024-07-25 06:25 UTC, hynseok commented on src/components/common/Header/Header.module.css
> +    padding: 10px 20px;
패딩이 조금 부족해보여서 
12px 24px로 수정하거나
<img width="383" alt="스크린샷 2024-07-25 오후 3 17 49" src="https://github.com/user-attachments/assets/fe5f388c-4f64-48f2-bc18-e31e90584534">

& > ul > li > ul 에 패딩을 5px 10px 정도 주고, 
& > ul > li > ul > li 에 border radius를 줘서

<img width="330" alt="스크린샷 2024-07-25 오후 3 16 42" src="https://github.com/user-attachments/assets/1f69796a-3056-4fff-a467-b8732113c64d">

이런 느낌으로 가면 조금 더 예쁠 것 같아요!

2024-07-26 05:15 UTC, moony1204 approved these changes
현석님 리뷰 내용 반영 이후 storybook, test 코드 작성되면 될 거 같습니다

2024-07-26 06:28 UTC, chunzhi23 commented on src/components/common/Header/Header.module.css
> +    padding: 10px 20px;
`12px 24px`로 수정해보았습니다!

2024-07-26 06:29 UTC, chunzhi23 commented on src/app/page.tsx
> +      <Header />
storybook 활용법을 몰랐어서 그렇게 두었네요 ;D

2024-07-27 05:12 UTC, chunzhi23 commented on src/components/common/Header/Header.module.css
> +  --color-coverHover: #303030;
제가 임의로 사용한 색상을 모아 한데 정리해두었습니다! 합병 이후 논의해 적용한다면 좋을 것 같습니다 :>

2024-07-31 05:30 UTC, hynseok approved these changes
수고하셨습니다🙇🏻‍♂️🙇🏻‍♂️

2024-07-31 07:07 UTC, merged