[FEAT] 로그인박스 추가
SystemConsultantGroup/s-top-frontend pull request #27
Opened 2024-07-19 07:22 UTC by moony1204

작성자: @moony1204 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 로그인박스 구현

## 비고

- 깡통입니당. 디자인만 구현되어 있습니다

2024-07-24 06:01 UTC, chunzhi23 reviewed
버튼을 이미지로 만들지 않고 Mantine Button을 사용해서 만들면 어떨까요?
leftsection에 아이콘(또는 이미지)를 넣고 스타일로 width를 설정하면 좋을 것 같다는 생각입니다.

2024-07-27 06:54 UTC, chunzhi23 requested changes
고생하셨습니다. 아래 수정사항 외에는 이후 라이트/다크 색상을 찬찬히 바꾸면 좋을 것 같습니다!

2024-07-27 06:54 UTC, chunzhi23 commented on src/components/common/LoginBox/LoginBox.module.css
> +    height: 570px;
로그인박스의 width와 height를 고정해두지 말고
1. flexbox로 그대로 둬서 이 컴포넌트를 사용하는 그릇이 맞추게 하거나
2. LoginBox props로 width와 height를 받아와서 `style={{width: width, height: height}}`와 같이 하면 어떨까요?

2024-07-27 06:54 UTC, chunzhi23 commented on src/components/common/LoginBox/LoginBox.module.css
> +    height: 90px;
로그인박스와 마찬가지로 `width: 100%`처럼 크기를 유동적으로 설정할 수 있게 하면 좋을 것 같습니다.

2024-07-27 06:54 UTC, chunzhi23 commented on src/components/common/LoginBox/LoginBox.tsx
> +            <img src="/images/naverLoginButton.png" alt="네이버 로그인" className={classes.button} />
로그인 버튼을 이미지 대신 크기가 유동적일 수 있게 Mantine Button을 사용해서 만들면 어떨까요?
leftsection에 아이콘(또는 이미지)를 넣고 스타일로 width를 설정하면 좋을 것 같다는 생각입니다.

2024-07-31 08:42 UTC, moony1204 commented on src/components/common/LoginBox/LoginBox.module.css
> +    height: 570px;
최대한 맞춰서 변경해보았습니다

2024-07-31 08:43 UTC, moony1204 commented on src/components/common/LoginBox/LoginBox.tsx
> +            <img src="/images/naverLoginButton.png" alt="네이버 로그인" className={classes.button} />
mantine button으로 수정하였습ㄴㅣ다

2024-07-31 08:54 UTC, chqkq approved these changes

2024-07-31 09:38 UTC, chunzhi23 approved these changes
고생하셨습니다!

2024-07-31 13:07 UTC, merged