[FEAT] 페이지네이션/AI hub 카드/게시글 상세보기/통계 보기 추가
SystemConsultantGroup/s-top-frontend pull request #29
Opened 2024-07-19 08:26 UTC by obinox

작성자: @obinox
issue: #10 

## 체크 리스트

- [X] 적절한 제목으로 수정했나요?
- [X] 상단에 이슈 번호를 기입했나요?
- [X] Target Branch를 올바르게 설정했나요?
- [X] Label을 알맞게 설정했나요?

## 작업 내역

- #19 
- #20 
- #21 
- #22

## 비고

- 폰트, 이미지 적용되지 않음.
- 통계 svg 작업 필요

close/resolve/fix #{이슈 번호 기입}

2024-07-25 08:35 UTC, hynseok requested changes
수고하셨습니다. 수정사항 확인 부탁드립니다!

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Pagination/Pagination.tsx
> +import { Group, Pagination, Text } from "@mantine/core";
useState를 써서 맨 위에 "use client"를 붙여주셔야 할 것 같습니다!

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Pagination/Pagination.tsx
> +      <Pagination.Root
*.* 형태의 문법은 경험상 넥스트 렌더링에서 문제가 생기는 경우가 많은 것 같더라구요.
PaginationRoot 와 같은 형태로 수정하면 좋을 것 같습니다!

(https://mantine.dev/guides/next/#compound-components-in-server-components 참고)

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Cards/Aihub/Aihub.tsx
> +        <Bookmark className={classes.Bookmark} />
북마크를 클릭하면 북마크 api를 호출할 수 있도록 버튼으로 감싸거나 이벤트핸들러를 추가하면 좋을 것 같습니다.

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Statics/Statics.tsx
직접 개발하느라 수고하셨습니다..
<img width="260" alt="스크린샷 2024-07-25 오후 5 24 28" src="https://github.com/user-attachments/assets/f2dc2258-e3eb-47a5-867e-8ba77b6a3740">
사진처럼 라벨링을 할 수 있도록 기능을 추가하면 좋을 것 같아요.

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Cards/ViewPostDetail/ViewPostDetail.module.css
폰트 사이즈를 vw로 수정하셨는데, 게시물같은 경우에는 사이즈가 고정돼있는게 좋은 것 같습니다!
반응형은 line break정도만 신경쓰면 될 것 같아요.

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Cards/ViewPostDetail/ViewPostDetail.tsx
> +export function Paginations({
컴포넌트 이름이 잘못되어있는 것 같습니다!
4~7번째 줄도 잘못 들어가있는 것 같네용

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Cards/ViewPostDetail/ViewPostDetail.tsx
> +  articles: string[];
게시물 내용은 문자열 배열이 아니라 하나의 문자열로 응답이 올거에요.
아마 문자열 안에 br태그가 있을거라서 따로 구분없이 바로 출력하면 될 것 같습니다.

2024-07-25 08:35 UTC, hynseok commented on src/components/common/Pagination/Pagination.tsx
> +  const pages = data.slice((page - 1) * show, page * show).map((e) => {
테스트용 데이터는 컴포넌트 외부로 분리하여야 할 것 같습니다. 혹은 Paginations 컴포넌트를 사용하는 테스트 tsx파일 하나를 더 만드셔도 될 것 같습니다!

2024-07-26 07:41 UTC, chqkq commented on src/components/common/Cards/ViewPostDetail/ViewPostDetail.module.css
아..! 제가 피그마 만들때 pretendard 폰트를 안 쓰고 만들어서 지금 폰트가 다른가봐요!!
제 기억으로는 기본 폰트가 pretendard였는데 폰트 바꿔주시면 좋을 것 같습니다!
헷갈리게 피그마 폰트 다른걸로 해둬서 죄송해요ㅠㅠ

2024-08-04 13:04 UTC, hynseok approved these changes
수고하셨습니다!

2024-08-06 05:10 UTC, merged