[FEAT] 게시판 (게시판 목록, 게시판 세부)
SystemConsultantGroup/s-top-frontend pull request #31
Opened 2024-07-21 13:01 UTC by chunzhi23

작성자: @chunzhi23
Issue: #5

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 게시판 목록과 세부 컴포넌트 코드를 작성하였습니다.

## 비고

- 반응형 디자인을 제외하고 PR 올렸습니다. 추후 논의가 필요해 보입니다.
- 글자와 배경색이 맞지 않아 색깔은 디자인 틀에 맞춰 기본값으로 두었습니다. 차차 맞추겠습니다.
- 디자인에 포함되어있던 공유와 프린트 버튼의 작동을 프론트로 구현하지 못했습니다. 이것도 함께 개발하면서 맞추겠습니다.

2024-07-25 07:38 UTC, hynseok requested changes
수고하셨습니다. 폰트 사이즈 정도 수정할 부분 있으니 확인 부탁드립니다!

2024-07-25 07:38 UTC, hynseok commented on src/components/common/Noticeboard/elements/NoticeHeading.tsx
> +  const SearchPlaceholder = classifier.searchPlaceholder;
(필수 아님)
이렇게 쓰셔도 되고, 
15번째 줄에서 classifier: { labels, defaultLabel, searchPlaceholder } 와같이 구조분해할당을 사용하여 쓰셔도 될 것 같아요.

2024-07-25 07:38 UTC, hynseok commented on src/components/common/Noticeboard/elements/NoticeItem.tsx
> +  const Date = date.getDate();
(수정이 필요한 부분은 아닙니다.)
const formattedDate = new Intl.DateTimeFormat('ko-KR', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date);
  
  Intl.DateTimeFormat을 사용하여 위와 같이 포맷팅을 할 수도 있습니다. 
  
  날짜를 사용할 일이 생각보다 많아서 나중에 논의 후에 위에서 만든 formatDate 함수처럼 포맷팅을 하는 모듈을 따로 분리해서 만들어도 좋을 것  같네요.

2024-07-25 07:38 UTC, hynseok commented on src/components/common/Noticeboard/Noticeboard.module.css
> +  font-size: 24px;
제목 폰트사이즈가 조금 커보여서 20px 정도로 줄이면 좋을 것 같습니다! (피그마는 16px인데 테스트해보니 너무 작더라구용..)

2024-07-25 07:38 UTC, hynseok commented on src/components/common/NoticeDetail/elements/NoticeDetailStage.tsx
> +          <Button className={styles.stageBtn} variant="transparent">
오.. 저는 투명한 버튼 만들때 그냥 UnstyledButton 컴포넌트를 사용했었는데, transparent를 사용하면 눌리는 효과는 가져갈 수 있겠네요. 하나 배워갑니다.

2024-07-26 05:32 UTC, moony1204 commented on src/components/common/NoticeDetail/NoticeDetail.story.tsx
수정이 되지 않은 공지의 경우 수정 일시를 undefined로 하기보단 작성 일시와 수정 일시를 동일하게 하는게 어떨까요?

2024-07-26 05:35 UTC, moony1204 commented on src/components/common/NoticeDetail/elements/NoticeDetailHead.tsx
수정이 되지 않은 공지의 경우 수정 일시를 undefined로 하기보단 작성 일시와 수정 일시를 동일하게 하는게 어떨까요?

2024-07-26 05:37 UTC, moony1204 commented on src/components/common/NoticeDetail/NoticeDetail.module.css
개인적으로는 stageResizePanel 사이즈가 좀 큰 거 같습니당.. padding과 폰트 사이즈를 줄여도 되지 않을까 싶습니다

2024-07-26 05:44 UTC, moony1204 commented on src/components/common/Noticeboard/Noticeboard.story.tsx
![스크린샷 2024-07-26 144311](https://github.com/user-attachments/assets/4d081e3e-7d41-4156-9da5-c8f4acf6b37d)
나중에는 라벨 디폴트를 전체로 두는 것이 어떨까요

2024-07-26 05:50 UTC, moony1204 commented on src/components/common/Noticeboard/Noticeboard.module.css
space-between 이어도 heading과 classifier label 사이의 최소 마진 설정 되어있으면 더 예쁠 거 같습니당

2024-07-26 05:52 UTC, moony1204 reviewed
classifier 내부 background color 지정되어 있을까요?

2024-07-27 03:56 UTC, chunzhi23 commented on src/components/common/Noticeboard/elements/NoticeHeading.tsx
> +  const SearchPlaceholder = classifier.searchPlaceholder;
아하 그런 방법이 있었군요! 감사합니다 :D

2024-07-27 03:58 UTC, chunzhi23 commented on src/components/common/Noticeboard/elements/NoticeItem.tsx
> +  const Date = date.getDate();
넵넵 공지사항 전체 리스트 조회 컴포넌트와 세부 컴포넌트 둘 다 사용하는데 사용하는 방법이 조금씩 달라서 이후에 함수 하나로 정리해보는 것이 좋을 것 같습니다!

2024-07-27 03:58 UTC, chunzhi23 commented on src/components/common/Noticeboard/Noticeboard.module.css
> +  font-size: 24px;
감사합니다 적용했습니다!

2024-07-27 04:03 UTC, chunzhi23 commented on src/components/common/NoticeDetail/elements/NoticeDetailStage.tsx
> +          <Button className={styles.stageBtn} variant="transparent">
우와 UnstyledButton이라는 컴포넌트를 놓칠 뻔 했네요 감사합니다 :>

2024-07-27 04:05 UTC, chunzhi23 commented on src/components/common/NoticeDetail/NoticeDetail.story.tsx
백앤드 팀에 물어보니 말씀주신대로 created_date와 edited_date가 최초 생성 시 같은 값으로 채워진다고 하시더라고요! 반영했습니다 :)

2024-07-27 04:06 UTC, chunzhi23 commented on src/components/common/NoticeDetail/NoticeDetail.module.css
panel 오른쪽에 있는 두 버튼 height와 맞추려고 크기가 커지게 되었습니다..!
한번 폰트를 줄여보았습니당

2024-07-27 04:07 UTC, chunzhi23 commented on src/components/common/Noticeboard/Noticeboard.story.tsx
제목 + 내용 라벨을 전체로 바꾸고 디폴트로 두어도 괜찮을 것 같습니다!

2024-07-27 04:07 UTC, chunzhi23 commented on src/components/common/Noticeboard/Noticeboard.module.css
flex-gap 20px으로 설정해두었습니다!

2024-07-27 04:09 UTC, chunzhi23 commented
> classifier 내부 background color 지정되어 있을까요?

mantine에서 기본으로 제공하는 배경색을 사용하고 있는 것 같습니다!

2024-07-27 04:15 UTC, chunzhi23 commented on src/components/common/NoticeDetail/NoticeDetail.module.css
> +}
제가 임의로 사용한 색깔 변수를 한데 모아 정리해두었습니다. 병합 이후 논의를 통해 반영해주시면 좋을 것 같다고 생각합니다!

2024-07-31 05:23 UTC, hynseok commented on src/components/common/Noticeboard/Noticeboard.module.css
> +  font-size: 24px;
넵 감사합니당

2024-07-31 05:28 UTC, hynseok approved these changes
코드량이 상당하네요.. 큰 컴포넌트라 만들기 어려우셨을텐데 수고하셨습니다!

2024-07-31 07:30 UTC, merged