[FEAT] 검색 입력
SystemConsultantGroup/s-top-frontend pull request #32
Opened 2024-07-21 13:46 UTC by chunzhi23

작성자: @chunzhi23 
Issue: #5 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 검색 입력 컴포넌트 코드를 작성했습니다.

## 비고

- 컴포넌트 배경 색깔을 지정하지 못했습니다. 함께 코딩하면서 맞춰나가면 좋을 것 같습니다.

2024-07-25 07:56 UTC, hynseok requested changes
간단한 수정사항 있으니 확인 부탁드립니다!

2024-07-25 07:56 UTC, hynseok commented on src/components/common/SearchInput/SearchInput.tsx
> +  return <Input placeholder={placeholder} {...props} />;
leftSection에 검색 아이콘을 고정해두는게 좋을 것 같아요. icon 크기도 props에 담아서 조절할 수 있도록 하면 좋을 것 같습니다!

2024-07-26 05:55 UTC, moony1204 commented on src/components/common/SearchInput/SearchInput.module.css
아이콘을 leftsection으로 한다면 아이콘 hover 상태일 때 커서 모양 바뀌게 하면 좋을 거 같습니다

2024-07-26 05:56 UTC, moony1204 reviewed
background color 지정도 되면 좋을 듯 합니다

2024-07-27 04:35 UTC, chunzhi23 commented on src/components/common/SearchInput/SearchInput.tsx
> +  return <Input placeholder={placeholder} {...props} />;
넵 그렇게 수정했습니다!
iconSize 기본값은 16으로 설정해두었습니다

2024-07-27 04:36 UTC, chunzhi23 commented on src/components/common/SearchInput/SearchInput.module.css
mantine에서 가져온 Input 컴포넌트인데 icon이 있는 곳까지 text area로 판정하는 것 같아서 안 되는 것 같습니다ㅠㅜ

2024-07-27 04:37 UTC, chunzhi23 commented
> background color 지정도 되면 좋을 듯 합니다

mantine에서 기본적으로 설정한 배경색을 사용했습니다!

2024-07-31 05:20 UTC, hynseok approved these changes
수고하셨습니다🙇🏻‍♂️

2024-07-31 07:31 UTC, merged