[FEAT] 필터칩 추가
SystemConsultantGroup/s-top-frontend pull request #34
Opened 2024-07-24 01:40 UTC by moony1204

작성자: @moony1204 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 필터칩 추가 작업

## 비고

- 필터칩 색상 랜덤으로 나오게 하였습니다

2024-07-24 06:38 UTC, chunzhi23 commented on src/components/common/FilterChips/ResetIcon.tsx
[Tabler Icons](https://tabler.io/icons)를 사용하면 관리가 편할 것 같습니다!

2024-07-27 07:12 UTC, chunzhi23 requested changes
고생하셨습니다. 아래 수정사항 외에는 이후 라이트/다크 색상을 찬찬히 바꾸면 좋을 것 같습니다!

2024-07-27 07:12 UTC, chunzhi23 commented on src/components/common/FilterChips/ResetIcon.tsx
Tabler Icons를 적용하는 데에 [여기](https://github.com/SystemConsultantGroup/s-top-frontend/pull/16#discussion_r1693889142)를 참고해 작업해주시면 좋겠습니다!

2024-07-27 07:12 UTC, chunzhi23 commented on src/components/common/FilterChips/FilterChip.tsx
> +      {!isReset && (
```
{ !isReset && (
  <>
    ...
  </>
)}
```

위와 같이 처리해도 괜찮을 것 같습니다!

2024-07-27 07:12 UTC, chunzhi23 commented on src/components/common/FilterChips/FilterChip.tsx
> +  return colors[Math.floor(Math.random() * colors.length)];
backgroundColor와 color를 `FilterChip`의 props로 받아오게 하면 좋을 것 같아요!

클립 색상을 어떻게 설정해야 하는지는 추후 논의가 필요할 것 같네요..! 노션에 올려두겠습니다 :)

2024-07-31 05:58 UTC, moony1204 commented on src/components/common/FilterChips/FilterChip.tsx
> +          <ResetIcon />
반영했습니다

2024-07-31 05:59 UTC, moony1204 commented on src/components/common/FilterChips/FilterChip.tsx
> +      {!isReset && (
tabler icon 적용하였고 resetchip class 새로 만들어 나누어 리턴하는 방식으로 수정했습니다

2024-07-31 05:59 UTC, moony1204 commented on src/components/common/FilterChips/FilterChip.tsx
> +  return colors[Math.floor(Math.random() * colors.length)];
요건 그냥 랜덤으로 되게 두었습니다

2024-07-31 06:03 UTC, merged

2024-08-02 06:39 UTC, chunzhi23 commented
고생하셨습니다