[Feat] 댓글, 관리자사전승인, 기업카드, 라디오버튼
SystemConsultantGroup/s-top-frontend pull request #35
Opened 2024-07-24 05:19 UTC by chqkq

작성자: @github_nickname

## 체크 리스트

- [ ] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [ ] Target Branch를 올바르게 설정했나요?
- [ ] Label을 알맞게 설정했나요?

## 작업 내역

- 작업한 내용을 간략하게 작성해주세요.

## 비고

- 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.

close/resolve/fix #{이슈 번호 기입}

2024-07-25 13:49 UTC, moony1204 commented on src/components/common/Buttons/AdminSignupPreview/AdminSignupPreview.module.css
Pretendard variable 문제일까요 ?? 폰트 색깔 지정 #000 필요한 듯 함

2024-07-25 13:56 UTC, moony1204 commented on src/components/common/Buttons/JobFairCard/JobFairCard.module.css
폰트 색상 피그마와 맞추기?

2024-07-25 14:00 UTC, moony1204 commented on src/components/common/Buttons/RadioButton/RadioButton.tsx
라디오버튼 unclicked일 때의 색상/디자인 clicked 의 색상반전으로도 가능한가용

2024-07-25 14:01 UTC, moony1204 reviewed
사소한 디자인 디테일 위주로 코멘트 남겼습니다

2024-07-26 06:27 UTC, chqkq commented on src/components/common/Buttons/CommentBox/CommentBox.module.css
어.. 그러게요 지금 보니까 딱히 표시가 되어있지는 않네요

2024-08-01 15:00 UTC, sera2002 requested changes
수고 많으셨습니다! 수정 요청 몇 가지 드렸으니 확인 부탁드립니다.

2024-08-01 15:00 UTC, sera2002 commented on src/components/common/Buttons/AdminSignupPreview/AdminSignupPreview.module.css
컴포넌트 경로 수정하셔야 할 것 같아요! 지금 컴포넌트 폴더들이 Buttons 폴더 안에 들어있어서, 이거를 common 폴더로 옮겨주시면 좋을 것 같습니다.

2024-08-01 15:00 UTC, sera2002 commented on src/components/common/Buttons/AdminSignupPreview/AdminSignupPreview.module.css
> +.table td {
td에 들어가있는 문자열 길이가 길어질 때의 처리를 따로 해주시는 게 좋을 것 같습니다!
현재는 문자열이 길어지는대로 테이블 너비도 함께 늘어나고 있는데, 이 테이블의 경우 "미리보기" 테이블이므로 꼭 전체 데이터를 보여줄 필요는 없을 것 같아서, 일단 길어지는 부분은 생략을 하거나 하는게 좋을 것 같습니다.

2024-08-01 15:00 UTC, sera2002 commented on src/components/common/Buttons/CommentBox/CommentBox.module.css
> +}
사소한 디자인적인 요소이긴 하지만, 첫 번째 댓글 위에 있는 `<div className={classes.divider}></div>`와 첫 번째 댓글의 간격을, 나머지 댓글들과 댓글들의 border-top과의 간격과 동일하게 설정해주시는게 조금 더 깔끔해보일 것 같습니다. 
여기에서 padding-top만 조정해주시면 될 것 같아요!

2024-08-01 15:00 UTC, sera2002 commented on src/components/common/Buttons/JobFairCard/JobFairCard.tsx
> +        <img src={logo} alt={`${company} logo`} />
보다 최적화된 이미지 로딩을 위해, `img` 태그 대신에 [next/image](https://nextjs.org/docs/pages/api-reference/components/image)에서 Image 컴포넌트를 불러와서 사용하시는 걸 추천드립니다.

2024-08-01 15:00 UTC, sera2002 commented on src/components/common/Buttons/JobFairCard/JobFairCard.module.css
> +  margin-bottom: 10px;
position 부분 길이가 길어져서 줄바꿈이 되는 경우에, line-height이 20~24px 정도로 설정 되어있는게 보기에 더 좋을 것 같습니다.

2024-08-01 15:00 UTC, sera2002 commented on src/components/common/Buttons/JobFairCard/JobFairCard.module.css
> +  display: flex;
여러 개의 태그가 들어올 경우, `flex-wrap: 'wrap'` 속성 사용해서 자동 줄바꿈되도록 설정해주시는 게 좋을 것 같습니다.

2024-08-02 06:55 UTC, chqkq commented on src/components/common/Buttons/CommentBox/CommentBox.module.css
> +}
우와 저도 그걸 조정하고싶었는데!! 어떻게 하는지 몰라서 냅뒀었거든요ㅠㅠㅠ 감사합니다!!

2024-08-02 06:55 UTC, chqkq commented on src/components/common/Buttons/AdminSignupPreview/AdminSignupPreview.module.css
> +.table td {
넹!! 알겠습니당 ㅎㅁㅎ

2024-08-04 13:29 UTC, sera2002 requested changes
추가로 발견한 수정사항 하나 더 확인해주시면 감사하겠습니다!

2024-08-04 13:29 UTC, sera2002 commented on src/components/common/CommentBox/CommentBox.tsx
> +            onKeyDown={handleKeyDown}
댓글에서 한글을 입력 후 엔터를 눌렀을 때, composition이 완료된 문자열(마지막 문자를 제외한 문자열)이 제출된 이후, 입력 중이었던 마지막 문자도 또 한 번 제출이 되어서, 총 2개의 댓글이 한 번에 입력되고 있습니다. 
이 문제를 해결하기 위해서, textarea의 `compositionstart`, `compositionend` 이벤트를 활용하여 composition이 진행중인 경우 제출이 되지 않도록(composition이 끝난 경우에만 제출) 처리를 해주시면 좋을 것 같습니다.

자세한 내용은 IME composition 관련하여 찾아보시면 됩니다!

```suggestion
  const [isComposing, setIsComposing] = useState(false);
  
  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setComment(e.target.value);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey && !isComposing) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (comment.trim()) {
      if (onSubmit) onSubmit(comment);
      setComments([...comments, { author: "사람", content: comment }]);
      setComment("");
    }
  };

  return (
    <div className={classes.commentBox}>
      <h3 className={classes.commentTitle}>댓글</h3>
      <form onSubmit={handleSubmit}>
        <div className={classes.textareaContainer}>
          <textarea
            className={classes.textarea}
            value={comment}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
            onCompositionStart={() => setIsComposing(true)}
            onCompositionEnd={() => setIsComposing(false)}
```

2024-08-11 06:33 UTC, sera2002 approved these changes
수고하셨습니다!

2024-08-16 05:37 UTC, merged