[FEAT] 체크박스 추가
SystemConsultantGroup/s-top-frontend pull request #36
Opened 2024-07-24 06:01 UTC by moony1204

작성자: @moony1204 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 체크박스 추가

## 비고

- clicked를 primary color로, unclicked 를 primary-container로 하였습니다

2024-07-24 07:18 UTC, chunzhi23 reviewed
Mantine에서 제공하는 component를 조금만 변형해서 그대로 사용해도 괜찮지 않을까는 생각이 들었습니다. [이걸](https://mantine.dev/core/checkbox/) 참고해주세요.

또한 [Tabler](https://tabler.io/icons)에서 아이콘을 가져오면 코드 관리가 편할 것 같습니다.

2024-07-24 08:05 UTC, chqkq commented on src/components/common/FilterChips/ResetIcon.tsx
전체해제 버튼 모양이 피그마 이미지랑 조금 다른 것 같아요!
옆에 테두리만 있어야되는데 테두리 색이 버튼 전체를 채운 듯 합니당

2024-07-27 07:24 UTC, chunzhi23 requested changes
고생하셨습니다. 커밋에 `CheckBox`뿐만 아니라 `FilterClip`까지 가져와진 것 같아서 이후에 병합 충돌이 있을 수 있으니 해당 브랜치에서는 삭제 정리해주시면 좋을 것 같습니다!

2024-07-27 07:24 UTC, chunzhi23 commented on src/components/common/CheckBox/CheckBox.tsx
> +    <div className={styles.checkboxContainer} onClick={handleClick}>
Mantine에서 제공하는 component를 조금만 변형해서 그대로 사용하는 게 편할 것 같다고 생각했습니다.

[여기](https://mantine.dev/core/checkbox/#usage)를 보시면 오른쪽에 checkbox의 상태를 바꿀 수 있는 선택이 여러 개 나와 있는데 이걸 CheckboxProps에 맞게 `checkBox`의 props로 받아오면 좋을 것 같습니다!

2024-07-31 06:49 UTC, moony1204 commented on src/components/common/FilterChips/ResetIcon.tsx
필터칩 브랜치에서 반영 수정 하였습니다

2024-07-31 08:11 UTC, moony1204 commented on src/components/common/CheckBox/CheckBox.tsx
> +    <div className={styles.checkboxContainer} onClick={handleClick}>
mantine으로 변경하엿습니다 label은 따로 뒀습니다

2024-07-31 08:18 UTC, merged

2024-08-02 06:42 UTC, chunzhi23 commented
고생하셨습니다