[Feat] 대담영상 카드 추가
SystemConsultantGroup/s-top-frontend pull request #38
Opened 2024-07-24 07:17 UTC by moony1204

작성자: @moony1204 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 대담영상 카드 추가

## 비고

- .

2024-07-24 08:06 UTC, chunzhi23 reviewed
[Tabler](https://tabler.io/icons)에서 아이콘을 가져오면 코드 관리가 편할 것 같습니다.

또한 사용자가 이전에 해당 영상에 북마킹했을 수 있으므로 marked도 props로 받아와야 할 것 같습니다.

2024-07-27 07:44 UTC, chunzhi23 requested changes
고생하셨습니다. 아래 수정사항 외에는 이후 라이트/다크 색상을 찬찬히 바꾸면 좋을 것 같습니다!

그리고 `CheckBox`와 `FilterChips`도 이 커밋에 함께 들어온 것 같은데 혹시 모를 충돌을 대비하기 위해 해당 브랜치에는 삭제 정리를 부탁드립니다🙏

2024-07-27 07:44 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.tsx
> +          <svg
Tabler Icons를 적용하는 데에 [여기](https://github.com/SystemConsultantGroup/s-top-frontend/pull/16#discussion_r1693889142)를 참고해 작업해주시면 좋겠습니다!

2024-07-27 07:44 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.tsx
> +          <svg
마찬가지로 주석을 달아주시거나 Tabler Icons를 적용해주시면 감사하겠습니다! Tabler Icons를 적용하는 건 [여기](https://github.com/SystemConsultantGroup/s-top-frontend/pull/16#discussion_r1693889142)를 참고해주세요!

2024-07-27 07:44 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.module.css
> +.button {
퀴즈 풀기 버튼에 padding을 5px 10px 정도 주면 좋을 것 같습니다.

2024-07-27 07:44 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.tsx
> +        <div className={styles.subtitle}>{subtitle}</div>
북마크 버튼과 퀴즈 풀기 버튼을 `position: absolute;`로 빼지 말고 `.details`에 `.subtitle` 다음으로 Mantine의 `<Group>`으로 묶어서 아래와 같이 작성하면 어떨까 생각합니다.

```
<Group justify="space-between">
  {/* 북마크 */}
  {/* 퀴즈풀기 */}
</Group>
```

mantine의 Group은 [여기](https://mantine.dev/core/group/)를 참고해주세요 :)

2024-07-27 07:44 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.tsx
> +  const [bookmarked, setBookmarked] = useState(false);
북마크 되어있는지 여부를 DB에서 받아올 것이니 props로 받아오면 좋을 것 같습니다!

2024-07-27 07:44 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.tsx
> +export const VideoCard: React.FC<VideoCardProps> = ({ title, subtitle, videoUrl }) => {
`React.FC`도 [이 오류](https://github.com/SystemConsultantGroup/s-top-frontend/pull/33#discussion_r1691004311)에 들어갈지 아닐지를 잘 모르겠어서

```
({title, subtitle, videoUrl}: VideoCardProps)
```

로 작성해주시는 게 안전할 것 같아요!

2024-07-31 08:56 UTC, chqkq approved these changes

2024-08-02 01:12 UTC, moony1204 commented on src/components/common/VideoCard/VideoCard.tsx
> +          <svg
다른 컴포넌트에서도 해당 아이콘이 사용되어 tabler로 바꾸지 않고 코멘트 추가했습니다

2024-08-02 01:13 UTC, moony1204 commented on src/components/common/VideoCard/VideoCard.module.css
> +.button {
버튼을 mantine 으로 교체하였습니다

2024-08-02 01:13 UTC, moony1204 commented on src/components/common/VideoCard/VideoCard.tsx
> +        <div className={styles.subtitle}>{subtitle}</div>
적용했습니다

2024-08-02 01:13 UTC, moony1204 commented on src/components/common/VideoCard/VideoCard.tsx
> +  const [bookmarked, setBookmarked] = useState(false);
props에 디폴트를 false로 하여 추가했습니다

2024-08-02 01:14 UTC, moony1204 commented on src/components/common/VideoCard/VideoCard.tsx
> +export const VideoCard: React.FC<VideoCardProps> = ({ title, subtitle, videoUrl }) => {
좀 찾아보고 useEffect로 북마크만 더 확인해 하이드레이션 방지할 수 있도록 해두었습니다

2024-08-02 10:35 UTC, chunzhi23 requested changes
마지막으로 한번만 더 확인해주시면 감사하겠습니다!

2024-08-02 10:35 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.module.css
> +  height: 281.82px;
이 컴포넌트를 페이지에 반영할 때는 아마도 grid를 써서 window의 너비에 따라 컴포넌트 너비를 반응형으로 결정하게 될 것 같아 width를 지정하지는 않아도 괜찮을 것 같습니다.

height는 .container가 포함하고 있는 요소들이 자동적으로 만들어낸 높이를 가지게 만들면 내용물이 길어져도 잘리지 않고 모든 내용물을 보여줄 수 있으니 height 또한 따로 지정하지 않아도 괜찮을 것 같습니다. 다만 height를 자동적으로 주기 위해서는 부모 position relative 자식 position absolute 관계를 없애야 합니다.

2024-08-02 10:35 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.module.css
> +}
position absolute로 하면 부모 노드에 height가 반영되지 않습니다. 따라서 차곡차곡 쌓아간다는 느낌으로 position을 설정하지 않으면 좋을 것 같다고 생각됩니다. 크기 또한 유동적으로 바뀌게 만들 수 있는 여지를 주기 위해 고정적인 수치를 설정하지 않으면 어떨까 생각합니다.

또한 left와 top로 중간을 맞추어주셨는데 이 부분은 부모 스타일에 display: flex를 활용하셔서 justify-content 또는 align-items style key를 활용해 정렬해주시는게 상자 크기가 달라져도 중간을 유지할 수 있도록 만들어줄 것입니다.

2024-08-02 10:35 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.module.css
> +}
부모 요소를 flexbox로 처리하면 .details에도 left와 top을 쓰지 않아도 됩니다.
또한 너비와 높이도 유동성을 위해 고정하지 않으면 좋을 것 같다고 생각합니다.

2024-08-04 04:39 UTC, chunzhi23 approved these changes
고생 많으셨습니다!

2024-08-04 04:39 UTC, chunzhi23 commented on src/components/common/VideoCard/VideoCard.module.css
> +  aspect-ratio: 16 / 9;
aspect-ratio라는 스타일 키로 비율 맞출 수 있는 줄 몰랐는데 배워갑니다 :D

2024-08-04 05:01 UTC, merged