[FEAT] 갤러리 미리보기 컴포넌트 추가
SystemConsultantGroup/s-top-frontend pull request #39
Opened 2024-07-25 14:51 UTC by sera2002

작성자: @sera2002
이슈: #8 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 갤러리 미리보기 컴포넌트를 개발했습니다.

## 비고

- 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.

close/resolve/fix #{이슈 번호 기입}

2024-07-27 11:32 UTC, chunzhi23 requested changes
고생하셨습니다. 아래 수정사항을 살펴봐주세요 :D

2024-07-27 11:32 UTC, chunzhi23 commented on .storybook/main.ts
> +  staticDirs: ["../public"],
제 storyview에는 왜 이미지가 반영 안 되나 궁금했는데 이렇게 추가할 수 있군요! 배워갑니다 :)

2024-07-27 11:32 UTC, chunzhi23 commented on src/components/common/GalleryPreview/GalleryPreview.tsx
> +              <Image
이미지 아이콘이 흐릿해서 잘 보이지 않을까 걱정되어 Tabler를 이용한 다른 방법을 추천드려보고 싶습니다!

[Tabler Icons](https://tabler.io/icons)에서 원하는 아이콘을 검색한 후 아래 빨간색 네모 박스 위치에 적혀있는 이름을 확인해주세요.
클릭하시면 복사가 됩니다!

![image](https://github.com/user-attachments/assets/be65e7c4-1e7c-4c4b-9818-e15a4cc9880c)

그럼 vscode에서 컴포넌트 같이 사용할 수 있습니다!

![image](https://github.com/user-attachments/assets/f2a57398-8838-487f-b26a-2acacd2f210f)

- size: 크기
- stroke: 굵기

참고해주시면 좋을 것 같습니다 :)

2024-07-27 11:32 UTC, chunzhi23 commented on src/components/common/GalleryPreview/GalleryPreview.tsx
> +        <Card.Section className={classes.image_section}>
`Card.Section`도 [이 오류](https://github.com/SystemConsultantGroup/s-top-frontend/pull/33#discussion_r1691004311)로 인해 `CardSection`으로 작성해주시는 게 안전할 것 같아요!

2024-08-07 06:56 UTC, obinox approved these changes

2024-08-08 15:10 UTC, sera2002 commented on src/components/common/GalleryPreview/GalleryPreview.tsx
> +              <Image
넵 수정했습니다!

2024-08-08 15:11 UTC, sera2002 commented on src/components/common/GalleryPreview/GalleryPreview.tsx
> +        <Card.Section className={classes.image_section}>
수정했습니다! 확인 부탁드려요 :)

2024-08-09 05:16 UTC, chunzhi23 approved these changes

2024-08-09 07:38 UTC, merged