[FEAT] 관리자 게시판 미리보기 컴포넌트 추가
SystemConsultantGroup/s-top-frontend pull request #40
Opened 2024-07-26 06:51 UTC by sera2002

작성자: @sera2002 
이슈: #8 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 관리자 게시판 미리보기 컴포넌트를 개발하였습니다.

## 비고

- 페이지 넘길 때 페이지네이션이 올라갔다 내려갔다 하는게 별로 좋아보이지 않는데 페이지네이션 위치를 고정하는 게 좋을까요?
- 컴포넌트 전체 높이도 아예 높이를 고정시키는게 좋을지 모르겠습니다.

close/resolve/fix #{이슈 번호 기입}

2024-07-27 11:57 UTC, chunzhi23 requested changes
고생하셨습니다.

페이지를 넘길 때 페이지네이션의 위치가 바뀌는 게 개인적으론 불편하다고 느껴 어느 정도 고정시켜두는 것이 편할 것 같다고 생각합니다.

페이지에 이 컴포넌트를 적용할 때 주어진 공간의 100%를 기본적으로 이 컴포넌트가 차지하도록 해서 가장 밑단에 페이지네이션을 고정시키고, 리스트가 100%를 넘기게 되면 그 때 리스트의 height에 따라 움직이게 하면 어떨까요?

2024-07-27 11:57 UTC, chunzhi23 commented on src/components/common/AdminNoticePreview/AdminNoticePreview.tsx
> +          <Image alt="table icon" src="/icons/Table.svg" width={24} height={24} />
아이콘이 얇아 잘 보이지 않는 것 같아 다른 아이콘 또는 [여기](https://github.com/SystemConsultantGroup/s-top-frontend/pull/39#discussion_r1693943125)를 참고해 Tabler를 사용하면 좋을 것 같습니다!

2024-07-27 11:57 UTC, chunzhi23 commented on src/components/common/AdminNoticePreview/AdminNoticePreviewRow/AdminNoticePreviewRow.tsx
> +        {pinned && <Image src="/icons/Pin_fill.svg" alt="pinned" width={24} height={24} />}
Pin 아이콘도 Tabler에 같은 모양이 있으니 [여기](https://github.com/SystemConsultantGroup/s-top-frontend/pull/39#discussion_r1693943125)를 참고해 편하게 쓰실 수 있을 것 같습니다!

2024-08-07 06:56 UTC, obinox approved these changes

2024-08-09 07:09 UTC, sera2002 commented
> 고생하셨습니다.
> 
> 페이지를 넘길 때 페이지네이션의 위치가 바뀌는 게 개인적으론 불편하다고 느껴 어느 정도 고정시켜두는 것이 편할 것 같다고 생각합니다.
> 
> 페이지에 이 컴포넌트를 적용할 때 주어진 공간의 100%를 기본적으로 이 컴포넌트가 차지하도록 해서 가장 밑단에 페이지네이션을 고정시키고, 리스트가 100%를 넘기게 되면 그 때 리스트의 height에 따라 움직이게 하면 어떨까요?

늦은 수정 죄송합니다. 마지막 페이지의 경우 dummyRow가 추가로 보여지도록 해서 페이지네이션을 고정시켰습니다. 수정된 코드 확인 부탁드립니다!

2024-08-09 07:10 UTC, sera2002 commented on src/components/common/AdminNoticePreview/AdminNoticePreview.tsx
> +          <Image alt="table icon" src="/icons/Table.svg" width={24} height={24} />
수정했습니다!

2024-08-09 07:10 UTC, sera2002 commented on src/components/common/AdminNoticePreview/AdminNoticePreviewRow/AdminNoticePreviewRow.tsx
> +        {pinned && <Image src="/icons/Pin_fill.svg" alt="pinned" width={24} height={24} />}
수정했습니다!

2024-08-09 14:26 UTC, chunzhi23 approved these changes
확인 감사합니다!
아래 한 가지 요청사항만 확인해주세요 :)

2024-08-09 14:26 UTC, chunzhi23 commented on src/components/common/AdminNoticePreview/AdminNoticePreview.module.css
> +  width: 600px;
부모 스타일에 맞게 유동적으로 너비가 변할 수 있도록 width를 고정하지는 않아도 괜찮을 것 같습니다!

2024-08-11 06:56 UTC, merged